# This is a generated file. Not intended for manual editing.
services:
  ambev.developerevaluation.webapi:
    build:
      context: "C:\\Users\\caioc\\OneDrive\\Downloads\\abi-gth-omnia-developer-evaluation.NET\\\
        template\\backend"
      dockerfile: "src/Ambev.DeveloperEvaluation.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ambevdeveloperevaluationwebapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "C:\\Users\\caioc\\OneDrive\\Downloads\\abi-gth-omnia-developer-evaluation.NET\\\
      template\\backend\\src\\Ambev.DeveloperEvaluation.WebApi:/app:rw"
    - "C:\\Users\\caioc\\OneDrive\\Downloads\\abi-gth-omnia-developer-evaluation.NET\\\
      template\\backend:/src:rw"
    - "C:\\Users\\caioc\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\caioc\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.2\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\caioc\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\caioc\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_5_13_14_33_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
